apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight-sidebar-topics-dropdown
  namespace: starlight-sidebar-topics-dropdown
  labels:
    app: starlight-sidebar-topics-dropdown
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starlight-sidebar-topics-dropdown
  template:
    metadata:
      labels:
        app: starlight-sidebar-topics-dropdown
    spec:
      containers:
        - name: starlight-sidebar-topics-dropdown
          image: "trueberryless/starlight-sidebar-topics-dropdown:main-915fe154b165d08bf0a90bfddd4dce2b8debf423"
          imagePullPolicy: Always
